"""add_uber_delivery_fields

Revision ID: 2514da200365
Revises: a701dc900855
Create Date: 2026-01-09 13:01:54.658443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2514da200365'
down_revision: Union[str, Sequence[str], None] = 'a701dc900855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_history_category_id', table_name='inventory_history')
    op.drop_index('ix_inventory_history_id', table_name='inventory_history')
    op.drop_table('inventory_history')
    op.add_column('orders', sa.Column('uber_quote_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('uber_delivery_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), server_default='0.0', nullable=False))
    op.add_column('restaurants', sa.Column('street', sa.String(length=255), nullable=True))
    op.add_column('restaurants', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('restaurants', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('restaurants', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('restaurants', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('restaurants', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('restaurants', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'longitude')
    op.drop_column('restaurants', 'latitude')
    op.drop_column('restaurants', 'country')
    op.drop_column('restaurants', 'postal_code')
    op.drop_column('restaurants', 'state')
    op.drop_column('restaurants', 'city')
    op.drop_column('restaurants', 'street')
    op.drop_column('orders', 'delivery_fee')
    op.drop_column('orders', 'uber_delivery_id')
    op.drop_column('orders', 'uber_quote_id')
    op.create_table('inventory_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('previous_stock', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('new_stock', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('performed_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='inventory_history_category_id_fkey'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], name='inventory_history_performed_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='inventory_history_pkey')
    )
    op.create_index('ix_inventory_history_id', 'inventory_history', ['id'], unique=False)
    op.create_index('ix_inventory_history_category_id', 'inventory_history', ['category_id'], unique=False)
    # ### end Alembic commands ###
