"""add_uber_tracking_url

Revision ID: acd083cd18ee
Revises: 2514da200365
Create Date: 2026-01-09 13:13:35.155798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acd083cd18ee'
down_revision: Union[str, Sequence[str], None] = '2514da200365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('uber_tracking_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'uber_tracking_url')
    # ### end Alembic commands ###
