"""add phone to restaurant

Revision ID: e2eb392c1ab0
Revises: 4b50b6a8172b
Create Date: 2026-01-09 17:35:53.455842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2eb392c1ab0'
down_revision: Union[str, Sequence[str], None] = '4b50b6a8172b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'phone_number')
    # ### end Alembic commands ###
