"""refactor_categories_to_global

Revision ID: f0f0fa29cc01
Revises: e2eb392c1ab0
Create Date: 2026-01-14 16:06:26.433260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f0fa29cc01'
down_revision: Union[str, Sequence[str], None] = 'e2eb392c1ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_user_product_favorite')
    )
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_index(op.f('ix_favorites_product_id'), 'favorites', ['product_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.drop_index('ix_categories_restaurant_id', table_name='categories')
    op.create_unique_constraint(None, 'categories', ['name'])
    op.drop_constraint('categories_restaurant_id_fkey', 'categories', type_='foreignkey')
    op.drop_column('categories', 'stock')
    op.drop_column('categories', 'restaurant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('stock', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.create_foreign_key('categories_restaurant_id_fkey', 'categories', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'categories', type_='unique')
    op.create_index('ix_categories_restaurant_id', 'categories', ['restaurant_id'], unique=False)
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_product_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_table('favorites')
    # ### end Alembic commands ###
